# Board dependent make definitions

# $Id$

# Copyright (C)2013-2015, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Board specific macro definitions

ifeq ($(BOARDNAME), OLIMEX_STM32_P103)
MCU		= stm32f103rb
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN0 -DBUTTON0_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN44 -DLED0_INPUT=GPIONPIN44IN -DLED0_OUTPUT=GPIOPIN44OUT -DLED0_ACTIVELOW
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), OLIMEX_STM32_P107)
MCU		= stm32f107rb
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN45 -DBUTTON0_INPUT=GPIOPIN45IN -DBUTTON0_ACTIVELOW
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN0 -DBUTTON1_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN38 -DLED0_INPUT=GPIONPIN38IN -DLED0_OUTPUT=GPIOPIN38OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN39 -DLED1_INPUT=GPIONPIN39IN -DLED1_OUTPUT=GPIOPIN39OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com3:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), STM32_VALUE_LINE_DISCOVERY)
MCU		= stm32f100rb
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN0 -DBUTTON0_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN41 -DLED0_INPUT=GPIONPIN41IN -DLED0_OUTPUT=GPIOPIN41OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN40 -DLED1_INPUT=GPIONPIN40IN -DLED1_OUTPUT=GPIOPIN40OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com1:115200,n,8,1"'
IOFLAGS		+= -DMAX_DEVICES=3
endif

ifeq ($(BOARDNAME), W5200E01_M3)
MCU		= stm32f103c8
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN0 -DLED0_INPUT=GPIONPIN0IN -DLED0_OUTPUT=GPIOPIN0OUT -DLED0_ACTIVELOW
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN1 -DLED0_INPUT=GPIONPIN1IN -DLED0_OUTPUT=GPIOPIN1OUT -DLED0_ACTIVELOW
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com1:115200,n,8,1"'
endif
