# STM32F4 family board specific make definitions

# $Id$

# Copyright (C)2015, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Board specific macro definitions

ifeq ($(BOARDNAME), FEZ_CERB40)
MCU		= stm32f405rg
BOARDFLAGS	+= -DSTM32F405xx -DHSE_PLL -DHSE_VALUE=12000000
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), NETDUINOPLUS2)
MCU		= stm32f405rg
BOARDFLAGS	+= -DSTM32F405xx -DHSE_PLL -DHSE_VALUE=25000000
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN10 -DLED0_INPUT=GPIOPIN10IN -DLED0_OUTPUT=GPIOPIN10OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), NUCLEO_F411RE)
MCU		= stm32f411re
BOARDFLAGS	+= -DSTM32F411xE -DHSE_PLL -DHSE_VALUE=8000000 -DHSE_BYPASS
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN45 -DBUTTON0_INPUT=GPIOPIN45IN -DBUTTON0_ACTIVELOW
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN5 -DLED0_INPUT=GPIOPIN5IN -DLED0_OUTPUT=GPIOPIN5OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
OPENOCDIF	= stlink-v2-1
endif

ifeq ($(BOARDNAME), STM32F4_DISCOVERY)
MCU		= stm32f407vg
BOARDFLAGS	+= -DSTM32F407xx -DHSE_PLL -DHSE_VALUE=8000000
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN0 -DBUTTON0_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN60 -DLED0_INPUT=GPIOPIN60IN -DLED0_OUTPUT=GPIOPIN60OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN61 -DLED1_INPUT=GPIOPIN61IN -DLED1_OUTPUT=GPIOPIN61OUT
BOARDFLAGS	+= -DLED2_PIN=GPIOPIN62 -DLED2_INPUT=GPIOPIN62IN -DLED2_OUTPUT=GPIOPIN62OUT
BOARDFLAGS	+= -DLED3_PIN=GPIOPIN63 -DLED3_INPUT=GPIOPIN63IN -DLED3_OUTPUT=GPIOPIN63OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), STM32F4_DISCOVERY_SHIELD)
# STM32F4-Discovery plugged into MikroElektronika STM32F4 Discovery Shield,
# which has an FT232RL connected to USART2
MCU		= stm32f407vg
BOARDFLAGS	+= -DSTM32F4_DISCOVERY
BOARDFLAGS	+= -DSTM32F407xx -DHSE_PLL -DHSE_VALUE=8000000
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN0 -DBUTTON0_INPUT=GPIOPIN0IN
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN60 -DLED0_INPUT=GPIOPIN60IN -DLED0_OUTPUT=GPIOPIN60OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN61 -DLED1_INPUT=GPIOPIN61IN -DLED1_OUTPUT=GPIOPIN61OUT
BOARDFLAGS	+= -DLED2_PIN=GPIOPIN62 -DLED2_INPUT=GPIOPIN62IN -DLED2_OUTPUT=GPIOPIN62OUT
BOARDFLAGS	+= -DLED3_PIN=GPIOPIN63 -DLED3_INPUT=GPIOPIN63IN -DLED3_OUTPUT=GPIOPIN63OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), STM32_M4_MINI)
MCU		= stm32f415rg
BOARDFLAGS	+= -DSTM32F415xx -DHSE_PLL -DHSE_VALUE=1600000
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN44 -DLED0_INPUT=GPIOPIN44IN -DLED0_OUTPUT=GPIOPIN44OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN45 -DLED1_INPUT=GPIOPIN45IN -DLED1_OUTPUT=GPIOPIN45OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com2:115200,n,8,1"'
endif

ifeq ($(BOARDNAME), STM32_M4_CLICKER)
MCU		= stm32f415rg
BOARDFLAGS	+= -DSTM32F415xx -DHSE_PLL -DHSE_VALUE=16000000
BOARDFLAGS	+= -DBUTTON0_PIN=GPIOPIN32 -DBUTTON0_INPUT=GPIOPIN32IN -DBUTTON0_ACTIVELOW
BOARDFLAGS	+= -DBUTTON1_PIN=GPIOPIN33 -DBUTTON1_INPUT=GPIOPIN33IN -DBUTTON1_ACTIVELOW
BOARDFLAGS	+= -DLED0_PIN=GPIOPIN1 -DLED0_INPUT=GPIOPIN1IN -DLED0_OUTPUT=GPIOPIN1OUT
BOARDFLAGS	+= -DLED1_PIN=GPIOPIN2 -DLED1_INPUT=GPIOPIN2IN -DLED1_OUTPUT=GPIOPIN2OUT
CONSOLEFLAGS	?= -DCONSOLE_SERIAL -DCONSOLE_PORT='"com1:115200,n,8,1"'
endif
