# Makefile for STM32F4xx USB CDC serial port library

# $Id$

# Copyright (C)2015, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

USBSERIALDIR	= $(MCUDIR)/usb_serial

CFLAGS		+= -I$(USBSERIALDIR)

USBCFLAGS	+= -Wall -ffunction-sections
USBCFLAGS	+= $(OPTFLAGS) $(CPUFLAGS) $(DEBUGFLAGS)
USBCFLAGS	+= -I$(ARMSRC)/include -I$(MCUDIR)
USBCFLAGS	+= -DUSE_STDPERIPH_DRIVER -DUSE_FULL_ASSERT
USBCFLAGS	+= -I$(USBSERIALDIR) -I$(USBSERIALDIR)/lib/inc

ifeq ($(BOARDNAME), FEZ_CERB40)
USBCFLAGS	+= -DSTM32F40_41xxx
endif

ifeq ($(BOARDNAME), NETDUINOPLUS2)
USBCFLAGS	+= -DSTM32F40_41xxx
endif

ifeq ($(BOARDNAME), STM32F4_DISCOVERY)
USBCFLAGS	+= -DSTM32F40_41xxx
endif

ifeq ($(BOARDNAME), STM32_F4_MINI)
USBCFLAGS	+= -DSTM32F40_41xxx
endif

ifeq ($(BOARDNAME), STM32_F4_CLICKER)
USBCFLAGS	+= -DSTM32F40_41xxx
endif

ifeq ($(BOARDNAME), NUCLEO_F411RE)
USBCFLAGS	+= -DSTM32F411xE
endif

.PHONY: usb_serial_lib

usb_serial_lib:
	for F in $(USBSERIALDIR)/*.c ; do $(MAKE) CFLAGS="$(USBCFLAGS)" $${F%.c}.o ; done
	$(MAKE) CFLAGS="$(USBCFLAGS)" $(USBSERIALDIR)/lib/src/misc.o
	$(MAKE) CFLAGS="$(USBCFLAGS)" $(USBSERIALDIR)/lib/src/stm32f4xx_exti.o
	$(MAKE) CFLAGS="$(USBCFLAGS)" $(USBSERIALDIR)/lib/src/stm32f4xx_gpio.o
	$(MAKE) CFLAGS="$(USBCFLAGS)" $(USBSERIALDIR)/lib/src/stm32f4xx_rcc.o
	$(FIND) $(USBSERIALDIR) -type f -name '*.o' -exec $(AR) crs lib$(MCU).a {} ";"

# Add to target lists

LIBTARGETS	+= usb_serial_lib
